angular.module 'IdleLands'
.constant 'EventIcons',
  'item-mod':         'fa-legal'
  'item-find':        'icon-feather'
  'item-enchant':     'fa-magic'
  'item-switcheroo':  'icon-magnet'
  'shop':             'fa-money'
  'shop-fail':        'fa-money'
  'profession':       'fa-child'
  'explore':          'fa-globe'
  'levelup':          'icon-universal-access'
  'achievement':      'fa-shield'
  'party':            'fa-users'
  'exp':              'fa-support'
  'gold':             'icon-money'
  'combat':           'fa-newspaper-o faa-pulse animated'
  'event':            'fa-gift faa-shake animated'
  'pet':              'fa-paw'
  'guild':            'fa-sitemap'
  'towncrier':        'fa-quote-left'